# Setup
title:        Build Break
tagline:      A site with a lot of notes!
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Alex James
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
