# Setup
title:        Build Break
tagline:      Build, break, then build again. 
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Alex James
  url:        mailto:alx.james@gmail.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
